version: 3.9

services:
  database:
    image: mariadb/server:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - dbdata:/var/lib/mariadb
    ports: 
      - "3306:3306"
  backend:
    image: ubuntu:latest
    restart: always
    depends_on:
     - database
    build: /gameserver-backend
    volumes:
      - backenddata:/var/lib/backend
    ports:
      - "50051:50051"