version: "3.9"

services:

  database:
    container_name: database
    image: mariadb/server:10.4
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - data-mariadb:/mariadb
    ports: 
      - "3306:3306"
    networks:
      - backend

  backend:
    container_name: backend
    environment:
      MYSQL_ADRESS: "database:3306"
      API_PORT: "7001"
      JWT_SECRET: "secret"
    depends_on:
     - database
    build: ./gameserver-backend
    volumes:
      - /var/lib/backend
    ports:
      - "7001:7001"
    networks:
      - backend
      - frontend

  frontend:
    container_name: frontend-dev
    depends_on:
     - backend
    build:
      context: ./gameserver-frontend
      dockerfile: Dockerfile
    volumes:
      - /var/lib/frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - frontend

volumes:
  data-mariadb:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge